# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

localhost_development:
  # backend:
  #   name: file-system
  #   api_root: /api
  display_url: http://localhost:8000

backend:
  name: github
  repo: erikdstock/eriks-dotcom # change
  branch: master

media_folder: static/assets
public_folder: assets
site_url: https://erik.netlify.com
publish_mode: editorial_workflow

collections:
  # - name: mdx
  #   label: Mdx Example
  #   description: Documentation
  #   folder: content/mdx
  #   extension: mdx
  #   format: frontmatter
  #   widget: mdx
  #   create: true
  #   fields:
  #     - { label: Title, name: title, widget: string, required: true }
  #     - { label: Body, name: body, widget: mdx }

  - name: blog
    label: Blog
    # TODO: Move this into content/blog ?
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: markdown }
