# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

localhost_development:
  backend:
    name: file-system
    api_root: /api
  display_url: http://localhost:8000
  publish_mode: simple

backend:
  name: github
  repo: erikdstock/gatsby-ts-2019 # change
  branch: master

media_folder: static/assets
public_folder: assets
site_url: https://festive-villani-316b3c.netlify.com
publish_mode: editorial_workflow

collections:
  # A Collection with a fixed group of pages (files)
  - name: pages
    format: frontmatter
    label: Pages
    files:
      # .md extension is ok here because it is in the gatsby-config for gatsby-mdx extensions
      - file: "content/pages/about.md"
        label: "About"
        name: "about"
        # All fields except `body` will be rendered as frontmatter for markdown posts
        fields:
          - {
              label: "Collection Name",
              name: "collectionName",
              default: "pages",
              widget: "hidden", # Just stick this value^ on the frontmatter
            }
          ## A hidden field like this can be used to dynamically name
          ## rendering templates in gatsby-node.js (so could the collectionName above)
          # - {
          #     label: "Template Key",
          #     name: "templateKey",
          #     widget: "hidden",
          #     default: "Basic",
          #   }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "mdx" }
  # A not-fixed collection uses the `folder` path relative to root
  - name: blog
    label: Blog
    create: true # Allowed to create new files; used with `folder|extension|format|slug` below (rather than `files` array)
    folder: content/blog # Where to look and save
    extension: mdx # Format to find and save
    format: "frontmatter" # Files get a yaml frontmatter section (everything but body field)
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Collection Name",
          name: "collectionName",
          widget: "hidden",
          default: "blog",
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }
      - { label: Body, name: body, widget: mdx }
